Feature/wise 0008 exception
Postech-Code-Wizards/food-wise-backend pull request #7
Opened 2024-12-10 23:31 UTC by VitorHugoSouza

Add exception and swagger

2024-12-11 00:07 UTC, andy-spch commented on foodWise/src/main/resources/api_errors.properties
acho que para padronização ficaria legal como você fez na outra pasta "api_error_en_US" ou se quiser simplificar pode manter "api_error_en", pois nossa aplicação terá apenas inglês e português.

2024-12-11 00:07 UTC, andy-spch commented on foodWise/src/main/resources/api_errors_pt_BR.properties
Verificar se a padronização sera "api_errors_pt.properties"

2024-12-11 18:47 UTC, ContagiousMisfit requested changes
Ficou mto show. Deixei uns comentários pra gnt pensar.

2024-12-11 18:47 UTC, ContagiousMisfit commented on foodWise/src/main/java/br/com/foodWise/foodWise/service/exceptions/user/UserNotFound.java
> +    public UserNotFound() {
Acredito que podemos mudar para Resource Not Found pois teremos essa exception para produtos, restaurantes, customers, etc, então usariamos um arquivo só e podemos customizar apenas a mensagem concatenando 'X' não encontrado

2024-12-11 18:47 UTC, ContagiousMisfit commented on foodwise/src/main/java/br/com/foodWise/foodWise/controllers/UserController.java
> +    private static final Logger logger = LoggerFactory.getLogger(UserController.class);
Poderiamos usar a anotação @ Sl4j. Acho boa prática porque padronizamos usando `log`  ao invés de instanciar o Logger.

2024-12-11 18:47 UTC, ContagiousMisfit commented on foodwise/src/main/java/br/com/foodWise/foodWise/service/UserService.java
> +        logger.info("Buscando usuario! ");
Logs menores podemos usar como debug. https://stackoverflow.com/questions/6860186/log-info-vs-log-debug 

DEBUG: Information **interesting for Developers,** when trying to debug a problem.
INFO: Information interesting for Support staff trying to figure out the context of **a given error**
WARN to FATAL: Problems and Errors depending on the level of damage.

2024-12-13 01:19 UTC, ContagiousMisfit approved these changes

2024-12-13 11:09 UTC, merged